"""
Shared utilities for the consolidated replication report.

All analysis scripts write their results into a single markdown file,
outputs/analysis_report.md

`run_all.py` runs the full pipeline and rebuilds every section.
"""

import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
REPORT_PATH = os.path.join(OUTPUT_DIR, "analysis_report.md")

REPORT_HEADER = (
    "# AI Fact-Checkers in the Wild — replication results\n"
    "\n"
    "Generated by the scripts in this repository (see README.md for the\n"
    "paper-to-code map). Each section is updated in place by the script that\n"
    "owns it; `python run_all.py` rebuilds the whole report.\n"
)

# Section order mirrors the paper (main text, then appendices).
SECTIONS = [
    ("dataset", "Dataset summary (Data and Methods)"),
    ("timing", "Timing and exposure"),
    ("rating-buckets", "Ratings by rater ideology (Figure 1)"),
    ("rating-models", "Rating-level mixed models (Table 1)"),
    ("hte", "Heterogeneity by modality and topic (Figures 2-3)"),
    ("common-rater", "common-rater note-level analysis"),
    ("text-features", "Note length, URLs, and cited domains"),
    ("mbfc", "MBFC source quality"),
    ("domain-quality", "Domain-quality robustness check"),
    ("rater-tags", "Rater-provided tags"),
    ("pairwise-bt", "Within-rater pairwise comparison"),
    ("rating-temporal", "Temporal dynamics of ratings"),
    ("rating-text-mediation", "Textual features as predictors of ratings"),
    ("rating-cited-domains", "Associations between frequently cited domains and ratings"),
    ("note-level", "Full-sample note-level outcomes"),
    ("robustness", "Note-level robustness checks"),
    ("win-rate", "Within-post pairwise comparison of note helpfulness scores"),
    ("topic-dist", "Topic distribution across post samples"),
    ("representativeness", "Rater representativeness"),
    ("both-notes", "Posts with both note types"),
]
_SECTION_IDS = [sid for sid, _ in SECTIONS]
_SECTION_TITLES = dict(SECTIONS)


def _begin(section_id: str) -> str:
    return f"<!-- BEGIN {section_id} -->"


def _end(section_id: str) -> str:
    return f"<!-- END {section_id} -->"


def _render_section(section_id: str, lines: list[str]) -> str:
    title = _SECTION_TITLES[section_id]
    body = "\n".join(lines).strip("\n")
    return f"{_begin(section_id)}\n## {title}\n\n{body}\n{_end(section_id)}"


def update_report_section(section_id: str, lines: list[str]) -> str:
    """
    Replace (or insert, respecting the canonical section order) one section of
    outputs/analysis_report.md. Returns the report path.
    """
    if section_id not in _SECTION_IDS:
        raise ValueError(f"Unknown report section: {section_id!r}")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    content = REPORT_HEADER
    if os.path.exists(REPORT_PATH):
        with open(REPORT_PATH) as f:
            content = f.read()

    rendered = _render_section(section_id, lines)
    begin, end = _begin(section_id), _end(section_id)

    if begin in content and end in content:
        head, rest = content.split(begin, 1)
        _, tail = rest.split(end, 1)
        content = head + rendered + tail
    else:
        # Insert before the first existing section that comes later in the
        # canonical order; otherwise append at the end.
        insert_at = len(content)
        for later_id in _SECTION_IDS[_SECTION_IDS.index(section_id) + 1 :]:
            pos = content.find(_begin(later_id))
            if pos != -1:
                insert_at = pos
                break
        content = (
            content[:insert_at].rstrip("\n")
            + "\n\n"
            + rendered
            + "\n\n"
            + content[insert_at:].lstrip("\n")
        )

    with open(REPORT_PATH, "w") as f:
        f.write(content.rstrip("\n") + "\n")
    return REPORT_PATH
